regen docs (#97)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -79,6 +79,21 @@ jobs:
           go-version-file: go.mod
           check-latest: true
       - run: PATH=$PATH:$GOPATH/bin make test
+  verify-docs:
+    name: Verify docs
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
+        with:
+          go-version-file: go.mod
+      - run: PATH=$PATH:$GOPATH/bin make generate-docs
+      - name: Verify Changed files
+        run: |
+          git diff --exit-code -- . || {
+            echo "::error Schema has changed changed. Please run 'make update-schema' and commit the changes."
+            exit 1
+          }
   lint:
     name: Lint
     runs-on: ubuntu-latest
